---
image:  duckdns
version: v0.6.32
name: DuckDNS
description: "[Duckdns](https://duckdns.org/) is a free service which will point a DNS (sub domains of duckdns.org) to an IP of your choice. The service is completely free, and doesn't require reactivation or forum posts to maintain its existence."
ext_release: 1.1.0
arch:
  - aarch64
  - x86_64
  - armv7
